<?php

namespace Database\Seeders;

use App\Models\Fournisseur;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Catalogue des fournisseurs (compagnies, mutuelles, grossistes) avec lesquels
 * le cabinet peut être partenaire ou courtier référencé. Idempotent (par nom).
 */
class FournisseurSeeder extends Seeder
{
    public function run(): void
    {
        $fournisseurs = [
            ['ABEILLE ASSURANCES [COURTAGE]', 'Compagnie d\'assurance — marque du groupe Aviva France.'],
            ['ACCELERANT INSURANCE [COURTAGE]', 'Gestionnaire de garanties collectives et prévoyance.'],
            ['ACHEEL [COURTAGE]', 'Habitation, flotte, RC pro — marché dommages.'],
            ['ADD VALUE', 'Courtier grossiste — prévoyance et épargne salariale.'],
            ['AG2R LA MONDIALE [COURTAGE]', 'Mutuelle interprofessionnelle — retraite, prévoyance, santé.'],
            ['AIG EUROPE [COURTAGE]', 'Compagnie internationale — dommages et responsabilité civile.'],
            ['AIRBAG', 'Assurance emprunteur innovante 100 % digitale.'],
            ['ALBINGIA [COURTAGE]', 'Courtier grossiste multi-branches.'],
            ['ALLIANZ [COURTAGE]', 'Compagnie d\'assurance tous risques.'],
            ['ALLIASS', 'Réseau conseil — santé, prévoyance, épargne.'],
            ['ALPTIS ASSURANCES [COURTAGE]', 'Marque de la Mutuelle de Poitiers — multirisques.'],
            ['ANTHELIO', 'Assurance santé, prévoyance et retraite.'],
            ['APICIL', 'Groupe de protection sociale — prévoyance et retraite.'],
            ['APRIL COURTAGE', 'Courtier grossiste — référentiel produits varié.'],
            ['ARDES [COURTAGE]', 'Assureur mutualiste — multirisques dommages.'],
            ['ASSURANCE CARE', 'Assurance santé pour profils spécifiques.'],
            ['ASSURANCE PLUS', 'Intermédiaire multidisciplinaire dommages.'],
            ['ASSURFRANCE [COURTAGE]', 'Assurance automobile pour conduites particulières.'],
            ['ASSURÉA INNOVATION', 'Assurtech — garanties modulaires santé.'],
            ['ATHEMA', 'Mutuelle — santé, prévoyance, épargne.'],
            ['AUDIENS', 'Assurance obsèques et prévoyance.'],
            ['AVENIR PREVOYANCE [COURTAGE]', 'Prévoyance collective et individuelle.'],
            ['AVICHA', 'Assurance santé collective.'],
            ['AVIVA FRANCE [COURTAGE]', 'Compagnie multibranche — marque Abeille.'],
            ['AXA FRANCE [COURTAGE]', 'Compagnie intégrée toutes branches.'],
            ['AXELIUM [COURTAGE]', 'Prévoyance des indépendants — marque de Allianz.'],
            ['BALOO COURTAGE', 'Plateforme de courtage santé / prévoyance.'],
            ['BELLES SANTÉ', 'Mutuelle santé nouvelle génération.'],
            ['BNPP CARDIF [COURTAGE]', 'Assurance emprunteur et épargne.'],
            ['BPCE ASSURANCES [COURTAGE]', 'Pôle assurances du groupe BPCE.'],
            ['CCAS PREVOYANCE', 'Prévoyance et protection des agents.'],
            ['CHUBB EUROPE [COURTAGE]', 'Compagnie spécialisée — biens et responsabilité.'],
            ['CIPRÉ ASSURANCES', 'Mutuelle — individuelle et entreprise.'],
            ['CLAYE CLAYES', 'Assurance agricole et professionnelle.'],
            ['COVEA PROTECTION [COURTAGE]', 'Marque dommages de Covéa (MMA, MAAF, GMF).'],
            ['CREDIT MUTUEL ASSURANCES [COURTAGE]', 'Assureur lié au groupe Crédit Mutuel.'],
            ['DELTA ASSURANCES [COURTAGE]', 'Compagnie dommages — particulier et entreprise.'],
            ['DINNO', 'Mutuelle santé et prévoyance digitale.'],
            ['DIOT SIACI [COURTAGE]', 'Courtage grossiste et grandes entreprises.'],
            ['DIRECT ASSURANCE [COURTAGE]', 'Assurance en ligne — auto, habitation, santé.'],
            ['ECA ASSURANCES', 'Automobile et habitation en ligne.'],
            ['EOLIS ASSURANCES', 'Compagnie marocaine cotée — marché international.'],
            ['EOVI MCD', 'Mutuelle de la fonction publique et du privé.'],
            ['EUREXO [COURTAGE]', 'Assureur mutualiste — santé et prévoyance.'],
            ['FIDÉLIA', 'Mutuelle régionale santé.'],
            ['FILIA MAIF [COURTAGE]', 'Assurance auto du groupe MAIF.'],
            ['FINDEO', 'Assureur santé et prévoyance collectives.'],
            ['FNAC ASSURANCES', 'Garantie multimédia et appareils connectés.'],
            ['FNPI MUTUELLE', 'Mutuelle des professions indépendantes.'],
            ['FRANCE A', 'Assurances agricoles — groupe Crédit Agricole.'],
            ['GAN PATRIMOINE [COURTAGE]', 'Épargne, retraite et prévoyance patrimoniale.'],
            ['GAZELO', 'Gestionnaire santé / prévoyance des indépendants.'],
            ['GENERALI FRANCE [COURTAGE]', 'Compagnie multibranche européenne.'],
            ['GFM ASSURANCES', 'Courtier grossiste — RC et flotte.'],
            ['GPS ADDEVIC', 'Groupe de protection sociale santé.'],
            ['GRAS SAVOYE [COURTAGE]', 'Courtage grossiste toutes branches.'],
            ['GROUPAMA [COURTAGE]', 'Groupe mutualiste toutes branches.'],
            ['GROUPE SPV', 'Assurance de personnes — santé et prévoyance.'],
            ['HARMONIE MUTUELLE', 'Mutuelle de la fonction publique.'],
            ['HDI GLOBAL [COURTAGE]', 'Assureur industriel — risques d\'entreprise.'],
            ['HENNER', 'Assurance santé et prévoyance des directeurs.'],
            ['HISPCOX [COURTAGE]', 'Compagnie spécialisée — risques d\'entreprise.'],
            ['INESSENCE', 'Assureur santé digital des indépendants.'],
            ['INTÉRIALE MUTUELLE', 'Mutuelle santé nationale.'],
            ['IZIIS [COURTAGE]', 'Plateforme d\'assurance connectée.'],
            ['KAELA', 'Mutuelle nouvelle génération santé.'],
            ['KINARY', 'Assurance habitation flexible.'],
            ['LA BANQUE POSTALE ASSURANCES [COURTAGE]', 'Pôle assurances de La Banque Postale.'],
            ['LA MEDICALE', 'Assurance mobilité de l\'assurance vie.'],
            ['LA MUTUELLE GÉNÉRALE [COURTAGE]', 'Mutuelle nationale santé.'],
            ['LAPEYRE', 'Assurance automobile et habitation.'],
            ['LÉONI GROUPE', 'Prévoyance collective et santé.'],
            ['LLOYD\'S FRANCE [COURTAGE]', 'Marché d\'assurance international.'],
            ['MACIF [COURTAGE]', 'Groupe mutualiste — santé, habitation, mobilité.'],
            ['MACSF', 'Mutuelle des professions de santé.'],
            ['MAIF [COURTAGE]', 'Mutuelle d\'assurance civique.'],
            ['MALAKOFF HUMANIS', 'Groupe de protection sociale — santé, prévoyance, retraite.'],
            ['MATMUT [COURTAGE]', 'Mutuelle automobile et multirisques.'],
            ['MAXMANCE', 'Santé prévoyance des indépendants.'],
            ['MERIDIAN ASSURANCES', 'Assureur santé international.'],
            ['MGEN SANTÉ', 'Mutuelle de l\'Éducation nationale.'],
            ['MIFINCO', 'Courtier grossiste habitation et flotte.'],
            ['MMA [COURTAGE]', 'Mutuelle des motards — toutes branches.'],
            ['MOUSTACHE ASSURANCES', 'Assurance deux-roues innovante.'],
            ['MUTUELLE DE POITIERS [COURTAGE]', 'Mutuelle multirisques dommages et santé.'],
            ['MUTUAELIS', 'Groupe mutualiste santé.'],
            ['NEXCESS', 'Courtier grossiste — risques agricoles.'],
            ['NICE ASSURANCES', 'Compagnie santé et prévoyance.'],
            ['OCEANE', 'Mutuelle d\'entreprise santé.'],
            ['ORADEA VIE', 'Assureur vie sans médecin.'],
            ['PACIFICA [COURTAGE]', 'Assureur dommages du Crédit Agricole.'],
            ['PASSEPORT SANTÉ', 'Mutuelle santé internationale.'],
            ['PREMIS DE VIE', 'Assurance de prêt immobilier.'],
            ['PREVOIR SANTÉ', 'Groupe prévoyance santé.'],
            ['PRISME COURTAGE', 'Courtage grossiste multi-branches.'],
            ['PRO BTP', 'Protection sociale du BTP.'],
            ['QBE EUROPE [COURTAGE]', 'Compagnie de dommages et responsabilité.'],
            ['RADIANCE ASSURANCE', 'Assurance habitation et véhicules.'],
            ['RANDSTAD SANTÉ', 'Mutuelle santé des travailleurs temporaires.'],
            ['RÉUNION ASSURANCE', 'Compagnie du groupe Axa.'],
            ['RGB COUVERTURE', 'Courtier grossiste — risques particuliers.'],
            ['SAINT-AIGNAN', 'Mutuelle de France — santé et prévoyance.'],
            ['SANTÉCLAIRE', 'Mutuelle santé des indépendants.'],
            ['SAMARCANDE', 'Complémentaire santé innovante.'],
            ['SCOR', 'Réassureur international.'],
            ['SÉQUIO BROKER', 'Courtage grossiste — habitat et pro.'],
            ['SFERIS', 'Mutuelle de la santé et du social.'],
            ['SG COURTAGE', 'Pôle assurance du groupe Société Générale.'],
            ['SMABTP [COURTAGE]', 'Mutuelle du BTP — RC décennale.'],
            ['SODEXO PRÉVOYANCE', 'Prévoyance et santé collective.'],
            ['SOLIMUT', 'Groupe mutualiste santé.'],
            ['SPB ASSURANCES', 'Courtage grossiste spécialisé.'],
            ['SWISS LIFE FRANCE', 'Assureur vie et santé.'],
            ['TAMASY', 'Assurance santé internationale.'],
            ['TARANIS [COURTAGE]', 'Compagnie dommages du groupe Aéma.'],
            ['THELEM [COURTAGE]', 'Mutuelle dommages du Sud-Ouest.'],
            ['UNIVERS ASSURANCES', 'Groupe d\'assurance de personnes.'],
            ['VERLINGUE', 'Courtier grossiste industriel.'],
            ['VERSCOT SPECIALTY', 'Assureur spécialisé — risques spéciaux.'],
            ['VIA SANTÉ', 'Mutuelle santé et prévoyance.'],
            ['VIVACY', 'Mutuelle santé digitale.'],
            ['WAKAM [COURTAGE]', 'Mutuelle santé sociale et responsable.'],
            ['WE ARE GROUPAMA', 'Marque digital du groupe Groupama.'],
            ['WHITE TIP', 'Assurance maritime et transport.'],
            ['ZIPI ASSURANCE', 'Assurance temporaire auto.'],
            ['ZOUF GROUP', 'Gestionnaire de groupes de protection.'],
        ];

        foreach ($fournisseurs as [$nom, $information]) {
            Fournisseur::firstOrCreate(
                ['nom' => $nom],
                ['id' => (string) Str::uuid(), 'nom' => $nom, 'information' => $information, 'actif' => true]
            );
        }
    }
}